swagger: "2.0"
info:
  version: "0.0.1"
  title: Visual Background
  description: Visual Background 
host: localhost:3000
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /background/{backgroundId}:
    parameters:
        - name: backgroundId
          in: path
          description: Stock PGi backgrounds by id
          required: true
          type: integer
    get:
      operationId: getBackground
      description: Returns Visual Background to the Caller for a given id
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VisualBackgroundResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: deleteBackground
      description: Deletes Visual Background to the Caller for a given id
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VisualBackgroundResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /background/upload/:
    post:
      operationId: uploadVisualBackground
      description: Caller can upload a custom visual background
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/VisualBackgroundResponse"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VisualBackgroundResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  VisualBackgroundResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
